class_name SkillIds
extends RefCounted

## Stable legacy IDs used by the Phase 3A foundation and its representative
## definitions. Other authored IDs remain valid StringName values and will be
## imported in later content phases.
const FORCE: StringName = &"force"
const MAGIC: StringName = &"magic"
const SPELLS: StringName = &"spells"
const DODGE: StringName = &"dodge"
const SWORD: StringName = &"sword"
const BLADE: StringName = &"blade"
const STAFF: StringName = &"staff"
const PARRY: StringName = &"parry"
const UNARMED: StringName = &"unarmed"
const LITERATE: StringName = &"literate"
const MUSIC: StringName = &"music"

## Active daemon/skill definitions that inherit std/skill.c::valid_learn().
## The constants keep registry coverage explicit without treating unknown IDs
## as permissive legacy skills.
const AXE: StringName = &"axe"
const CHANTING: StringName = &"chanting"
const DAGGER: StringName = &"dagger"
const FORK: StringName = &"fork"
const HAMMER: StringName = &"hammer"
const INSTRUMENTS: StringName = &"instruments"
const IRON_CLOTH: StringName = &"iron-cloth"
const MOVE: StringName = &"move"
const PERCEPTION: StringName = &"perception"
const SPIDER_ARRAY: StringName = &"spider-array"
const STEALING: StringName = &"stealing"
const THROWING: StringName = &"throwing"
const WHIP: StringName = &"whip"
const YIRONG: StringName = &"yirong"

const FONXAN_FORCE: StringName = &"fonxanforce"
const FONXAN_SWORD: StringName = &"fonxansword"
const ESSENCE_MAGIC: StringName = &"essencemagic"
const FALL_STEPS: StringName = &"fall-steps"
const CELESTIAL: StringName = &"celestial"
const NINE_MOON: StringName = &"nine-moon"
const NINE_MOON_SWORD: StringName = &"nine-moon-sword"
const SIX_CHAOS_SWORD: StringName = &"six-chaos-sword"
const STORMDANCE: StringName = &"stormdance"
const TAO_MYSTERY: StringName = &"tao-mystery"

## Active daemon/skill valid_learn() policy IDs migrated in Phase 3C2.
const BLOODY_STRIKE: StringName = &"bloodystrike"
const BOLOMIDUO: StringName = &"bolomiduo"
const BUDDHISM: StringName = &"buddhism"
const CELESTRIKE: StringName = &"celestrike"
const CHAOS_STEPS: StringName = &"chaos-steps"
const CLOUDSTAFF: StringName = &"cloudstaff"
const DEISWORD: StringName = &"deisword"
const GOUYEE: StringName = &"gouyee"
const ICEFORCE: StringName = &"iceforce"
const JIN_GANG: StringName = &"jin-gang"
const JINGANG_STAFF: StringName = &"jingang-staff"
const JUECHEN_FORCE: StringName = &"juechen-force"
const LINBO_STEPS: StringName = &"linbo-steps"
const LIUH_KEN: StringName = &"liuh-ken"
const LOTUSFORCE: StringName = &"lotusforce"
const MAGIC_ARRAY: StringName = &"magic-array"
const MEIHUA_SHOU: StringName = &"meihua-shou"
const MYSTERRIER: StringName = &"mysterrier"
const MYSTFORCE: StringName = &"mystforce"
const MYSTSWORD: StringName = &"mystsword"
const NECROMANCY: StringName = &"necromancy"
const NOTRACES: StringName = &"notraces"
const PYROBAT_STEPS: StringName = &"pyrobat-steps"
const QIDAOFORCE: StringName = &"qidaoforce"
const SCRATCHING: StringName = &"scratching"
const SERPENTFORCE: StringName = &"serpentforce"
const SHORTSONG_BLADE: StringName = &"shortsong-blade"
const SNOWSHADE_FORCE: StringName = &"snowshade-force"
const SNOWSHADE_SWORD: StringName = &"snowshade-sword"
const SNOWWHIP: StringName = &"snowwhip"
const SPICYCLAW: StringName = &"spicyclaw"
const SPRING_BLADE: StringName = &"spring-blade"
const TAOISM: StringName = &"taoism"
const TENDERZHI: StringName = &"tenderzhi"
const TS_FIST: StringName = &"ts-fist"
const WU_SHUN: StringName = &"wu-shun"

## Referenced by nine-moon.c, but no active daemon/skill source exists.
const NINE_MOON_FORCE: StringName = &"nine-moon-force"
