class_name ItemSpawnDefinition
extends RefCounted

## Items an ES2 room places on its floor (`set("objects")` naming an item, not
## an NPC): one item lies on each spawn marker when the world is created.
## `item_spawns[]` in game/data, generated by the content importer.
var _spawn_id: StringName
var _item_definition_id: StringName
var _map_id: StringName
var _zone_id: StringName
var _spawn_point_ids: Array[StringName] = []
var _legacy_source_room_path: String
var _legacy_quantity: int

var spawn_id: StringName:
	get:
		return _spawn_id
var item_definition_id: StringName:
	get:
		return _item_definition_id
var map_id: StringName:
	get:
		return _map_id
var zone_id: StringName:
	get:
		return _zone_id
var legacy_source_room_path: String:
	get:
		return _legacy_source_room_path
var legacy_quantity: int:
	get:
		return _legacy_quantity


static func from_record(reader: ContentRecordReader) -> ItemSpawnDefinition:
	var points: Array[StringName] = []
	for id: String in reader.text_list("points"):
		points.append(StringName(id))
	var definition: ItemSpawnDefinition = ItemSpawnDefinition.new()
	definition._spawn_id = StringName(reader.required_text("id"))
	definition._item_definition_id = StringName(reader.required_text("item"))
	definition._map_id = StringName(reader.required_text("map"))
	definition._zone_id = StringName(reader.required_text("zone"))
	definition._spawn_point_ids = points
	definition._legacy_source_room_path = reader.required_text("legacy_room")
	definition._legacy_quantity = reader.required_integer("legacy_quantity")
	reader.finish()
	if not definition.is_valid():
		reader.fail("", "is not a valid item spawn (points must be unique and match legacy_quantity)")
	return definition


func spawn_point_ids() -> Array[StringName]:
	return _spawn_point_ids.duplicate()


## The item lying on `spawn_point_id` until someone takes it. Derived, so a
## save needs no position for it: the item record's WORLD parent says it is
## still there.
static func item_instance_id(scope: StringName, spawn_point_id: StringName) -> StringName:
	return StringName("%s.%s.item" % [String(scope), String(spawn_point_id)])


func is_valid() -> bool:
	if (
		_spawn_id.is_empty() or _item_definition_id.is_empty() or _map_id.is_empty() or _zone_id.is_empty()
		or _legacy_source_room_path.is_empty() or _spawn_point_ids.is_empty()
		or _spawn_point_ids.size() != _legacy_quantity
	):
		return false
	var seen: Dictionary[StringName, bool] = {}
	for id: StringName in _spawn_point_ids:
		if id.is_empty() or seen.has(id):
			return false
		seen[id] = true
	return true
