class_name ItemSpawnDefinition
extends RefCounted

## Items an ES2 room places on its floor (`set("objects")` naming an item, not
## an NPC): one item lies on each spawn marker when the world is created.
## `item_spawns[]` in game/data, generated by the content importer.
var _spawn_id: StringName
var _item_definition_id: StringName
var _map_id: StringName
var _zone_id: StringName
var _spawn_point_ids: Array[StringName] = []
var _legacy_source_room_path: String
var _legacy_quantity: int

var spawn_id: StringName:
	get:
		return _spawn_id
var item_definition_id: StringName:
	get:
		return _item_definition_id
var map_id: StringName:
	get:
		return _map_id
var zone_id: StringName:
	get:
		return _zone_id
var legacy_source_room_path: String:
	get:
		return _legacy_source_room_path
var legacy_quantity: int:
	get:
		return _legacy_quantity


func _init(
	p_spawn_id: StringName = &"",
	p_item_definition_id: StringName = &"",
	p_map_id: StringName = &"",
	p_zone_id: StringName = &"",
	p_spawn_point_ids: Array[StringName] = [],
	p_legacy_source_room_path: String = "",
	p_legacy_quantity: int = 0,
) -> void:
	_spawn_id = p_spawn_id
	_item_definition_id = p_item_definition_id
	_map_id = p_map_id
	_zone_id = p_zone_id
	_spawn_point_ids = p_spawn_point_ids.duplicate()
	_legacy_source_room_path = p_legacy_source_room_path
	_legacy_quantity = p_legacy_quantity


static func from_record(reader: ContentRecordReader) -> ItemSpawnDefinition:
	var points: Array[StringName] = []
	for id: String in reader.text_list("points"):
		points.append(StringName(id))
	var definition: ItemSpawnDefinition = ItemSpawnDefinition.new(
		StringName(reader.required_text("id")),
		StringName(reader.required_text("item")),
		StringName(reader.required_text("map")),
		StringName(reader.required_text("zone")),
		points,
		reader.required_text("legacy_room"),
		reader.required_integer("legacy_quantity"),
	)
	reader.finish()
	if not definition.is_valid():
		reader.fail("", "is not a valid item spawn (points must be unique and match legacy_quantity)")
	return definition


func spawn_point_ids() -> Array[StringName]:
	return _spawn_point_ids.duplicate()


## The item lying on `spawn_point_id` until someone takes it. Derived, so a
## save needs no position for it: the item record's WORLD parent says it is
## still there.
static func item_instance_id(scope: StringName, spawn_point_id: StringName) -> StringName:
	return StringName("%s.%s.item" % [String(scope), String(spawn_point_id)])


func is_valid() -> bool:
	if (
		_spawn_id.is_empty() or _item_definition_id.is_empty() or _map_id.is_empty() or _zone_id.is_empty()
		or _legacy_source_room_path.is_empty() or _spawn_point_ids.is_empty()
		or _spawn_point_ids.size() != _legacy_quantity
	):
		return false
	var seen: Dictionary[StringName, bool] = {}
	for id: StringName in _spawn_point_ids:
		if id.is_empty() or seen.has(id):
			return false
		seen[id] = true
	return true
