#!/usr/bin/env python3
"""Extract the game's player text into a gettext template (game/locale/eastern_stories.pot).

The source language is Simplified Chinese: a message's ID is its source text. Godot's own
POT generator cannot run from the command line, does not see TranslationServer.translate()
(which non-Node code uses) nor const tables, and never reads the JSON content, so this tool
is the one extractor. It reads:

* GDScript (game/, without tests/ and addons/): the literal first argument (and literal
  context) of tr(), atr() and TranslationServer.translate(), and every other string literal
  that holds Chinese text. A `# NO_TRANSLATE` comment on the line, or in the comment lines
  right above it, leaves a literal out (Godot's convention); `# TRANSLATORS: ...` there
  becomes a note for the translator.
* Scenes (.tscn): text, tooltip_text, placeholder_text, title and popup item texts, except
  on nodes whose auto_translate_mode is disabled.
* The content files listed in game/data/content_manifest.json: the fields that are player
  text (names, descriptions, lines, topics...), see `_walk_json`.

`--check` fails when the committed template is out of date. `lint_concatenation()` reports
Chinese text glued to other text with `+`, which a translator cannot reorder.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path


REPOSITORY = Path(__file__).resolve().parents[2]
GAME = "game"
POT_PATH = "game/locale/eastern_stories.pot"
MANIFEST = "game/data/content_manifest.json"
# Never shipped as player screens: the developer combat slice and an addon test scene.
DEV_ONLY_SCENES = frozenset({"scenes/combat/combat_vertical_slice.tscn", "scenes/mcp_test.tscn"})
SKIPPED_DIRECTORIES = ("tests/", "addons/")
TRANSLATE_CALLS = frozenset({"tr", "atr", "translate"})
SCENE_TEXT_PROPERTIES = frozenset({"text", "tooltip_text", "placeholder_text", "title"})
# Content fields whose string values are player text.
TEXT_KEYS = frozenset({
    "name", "short", "long", "title", "nickname", "say", "emote", "fail", "accept_say",
    "refuse_say", "dry_say", "respect", "unit", "base_unit", "action", "then", "else", "gender",
    "damage_type", "done", "weapon_fail", "improved_line", "message", "line",
    "target", "quest_type", "ask_say", "again_say", "oath", "ask_tell", "success", "force_fail",
    "whisper", "commoners_only",
})
TEXT_LIST_KEYS = frozenset({"limbs", "name_pick"})
# Inside lines and messages `action` names a chat function (random_move, drink, perform...), not a label.
LINE_KEYS = (TEXT_KEYS - {"action"}) | frozenset({
    "open", "close", "push", "hold", "fall", "climb", "climb_observer", "fall_observer",
    "use", "bury", "book", "paper", "shout", "shut", "joined", "refused",
    "weak", "rolled", "search", "found", "nothing", "spawn", "list",
})
# Lists of identifiers inside walked text (an inquiry rule's marks), never shown.
ID_LIST_KEYS = frozenset({"asker_marks", "unmark_giver"})
HEADER = """\
# Eastern Stories translation template.
# Source language: Simplified Chinese (zh_CN); each message ID is the source text.
# Generated by tools/l10n/extract_pot.py from the scripts, scenes and content files: do not edit.
# Keep every placeholder: {name} slots, %s and %d are filled by the game; in ES2 lines $N is the
# actor, $n the target, $p and $P their pronouns, $l a body part, $w a weapon, $RESPECT and $SELF
# forms of address. A {name} slot may be moved or, if the language has no use for it, left out.
msgid ""
msgstr ""
"Project-Id-Version: Eastern Stories\\n"
"MIME-Version: 1.0\\n"
"Content-Type: text/plain; charset=UTF-8\\n"
"Content-Transfer-Encoding: 8bit\\n"
"Language: zh_CN\\n"
"""

_CJK = re.compile("[\u3000-\u303f\u3400-\u4dbf\u4e00-\u9fff\uf900-\ufaff\uff00-\uffef]")
_IDENTIFIER_BEFORE_PAREN = re.compile(r"([A-Za-z_][A-Za-z0-9_]*)\s*\(\s*$")
_ESCAPES = {"n": "\n", "t": "\t", "r": "\r", "a": "\a", "b": "\b", "f": "\f", "v": "\v",
            "\\": "\\", '"': '"', "'": "'", "\n": ""}


@dataclass
class Entry:
    msgid: str
    context: str = ""
    notes: list[str] = field(default_factory=list)
    sources: list[str] = field(default_factory=list)


class Catalog:
    def __init__(self) -> None:
        self._entries: dict[tuple[str, str], Entry] = {}

    def add(self, msgid: str, source: str, *, context: str = "", note: str = "") -> None:
        if not msgid.strip():
            return
        entry = self._entries.setdefault((context, msgid), Entry(msgid, context))
        if note and note not in entry.notes:
            entry.notes.append(note)
        if source not in entry.sources:
            entry.sources.append(source)

    def entries(self) -> list[Entry]:
        return list(self._entries.values())

    def has(self, msgid: str, context: str = "") -> bool:
        return (context, msgid) in self._entries


@dataclass
class Literal:
    value: str
    line: int
    start: int
    end: int
    prefix: str


@dataclass
class Script:
    literals: list[Literal]
    comments: dict[int, str]
    comment_only_lines: set[int]


def has_chinese(text: str) -> bool:
    return _CJK.search(text) is not None


# --- GDScript --------------------------------------------------------------------------


def scan_gdscript(source: str) -> Script:
    """Splits GDScript source into string literals and comments (by line, 1-based)."""
    literals: list[Literal] = []
    comments: dict[int, str] = {}
    code_lines: set[int] = set()
    index, line, length = 0, 1, len(source)
    while index < length:
        char = source[index]
        if char == "\n":
            line += 1
            index += 1
        elif char == "#":
            end = source.find("\n", index)
            end = length if end < 0 else end
            comments[line] = source[index:end]
            index = end
        elif char in "\"'":
            prefix = source[index - 1] if index > 0 and source[index - 1] in "&^r" else ""
            start, start_line = index, line
            value, index, line = _read_string(source, index, line, raw=prefix == "r")
            literals.append(Literal(value, start_line, start, index, prefix))
            code_lines.add(start_line)
        else:
            if not char.isspace():
                code_lines.add(line)
            index += 1
    comment_only = {number for number in comments if number not in code_lines}
    return Script(literals, comments, comment_only)


def _read_string(source: str, index: int, line: int, *, raw: bool) -> tuple[str, int, int]:
    quote = source[index]
    triple = source.startswith(quote * 3, index)
    delimiter = quote * 3 if triple else quote
    index += len(delimiter)
    parts: list[str] = []
    while index < len(source):
        if source.startswith(delimiter, index):
            return "".join(parts), index + len(delimiter), line
        char = source[index]
        if char == "\\" and index + 1 < len(source):
            following = source[index + 1]
            if raw:
                parts.append(char + following)
                index += 2
            elif following in "uU":
                width = 4 if following == "u" else 6
                parts.append(chr(int(source[index + 2:index + 2 + width], 16)))
                index += 2 + width
            else:
                parts.append(_ESCAPES.get(following, following))
                line += following == "\n"
                index += 2
            continue
        if char == "\n":
            if not triple:
                raise ValueError(f"unterminated string on line {line}")
            line += 1
        parts.append(char)
        index += 1
    raise ValueError(f"unterminated string starting on line {line}")


def _directive(script: Script, line: int) -> tuple[bool, str]:
    """(skip, translator note) from the line's own comment or the comment lines above it."""
    candidates: list[str] = []
    if line in script.comments:
        candidates.append(script.comments[line])
    above = line - 1
    while above in script.comment_only_lines:
        candidates.append(script.comments[above])
        above -= 1
    for comment in candidates:
        text = comment[1:].strip() if comment.startswith("#") else comment.strip()
        if text == "NO_TRANSLATE" or text.startswith("NO_TRANSLATE:"):
            return True, ""
        if text.startswith("TRANSLATORS:"):
            return False, text[len("TRANSLATORS:"):].strip()
    return False, ""


def _call_name(source: str, literal: Literal) -> str:
    """The function a literal is the first argument of, or ''."""
    start = literal.start - (1 if literal.prefix else 0)
    match = _IDENTIFIER_BEFORE_PAREN.search(source[max(0, start - 80):start])
    return match.group(1) if match else ""


def _second_argument(source: str, literal: Literal, script: Script) -> tuple[bool, Literal | None]:
    """tr("x") -> (True, None); tr("x", "ctx") -> (True, <"ctx">); tr("x", ctx) -> (False, None)."""
    rest = source[literal.end:]
    stripped = rest.lstrip()
    if not stripped.startswith(","):
        return True, None
    after_comma = literal.end + len(rest) - len(stripped) + 1
    following = next((item for item in script.literals if item.start >= after_comma), None)
    if following is None or source[after_comma:following.start].strip() not in ("", "&"):
        return False, None
    return True, following


def extract_gdscript(source: str, relative: str, catalog: Catalog) -> None:
    script = scan_gdscript(source)
    contexts: set[int] = set()
    for literal in script.literals:
        if literal.prefix == "^" or literal.start in contexts:
            continue
        skip, note = _directive(script, literal.line)
        if skip:
            continue
        if _call_name(source, literal) in TRANSLATE_CALLS:
            # Godot's rule: a message whose context is not a literal is not extracted.
            literal_context, context = _second_argument(source, literal, script)
            if not literal_context:
                continue
            if context is not None:
                contexts.add(context.start)
            catalog.add(literal.value, relative, context="" if context is None else context.value, note=note)
        elif has_chinese(literal.value):
            catalog.add(literal.value, relative, note=note)


def lint_concatenation(source: str, relative: str) -> list[str]:
    """Chinese literals glued with `+`: they become fragments no translator can reorder."""
    script = scan_gdscript(source)
    errors: list[str] = []
    for literal in script.literals:
        if not has_chinese(literal.value) or _directive(script, literal.line)[0]:
            continue
        start = literal.start - (1 if literal.prefix else 0)
        before = source[:start].rstrip()
        after = source[literal.end:].lstrip()
        if before.endswith(("+", "+=")) or after.startswith("+"):
            errors.append(f"{relative}:{literal.line}: Chinese text joined with '+': {literal.value!r}")
    return errors


# --- Scenes -----------------------------------------------------------------------------

_SCENE_SECTION = re.compile(r"^\[(\w+)")
# A string property; Godot writes a multi-line value with real line breaks inside the quotes.
_SCENE_PROPERTY = re.compile(r'^([A-Za-z0-9_/]+) = "((?:[^"\\]|\\.)*)"\s*$', re.MULTILINE | re.DOTALL)


def extract_scene(text: str, relative: str, catalog: Catalog) -> None:
    pending: list[str] = []
    disabled = False

    def flush() -> None:
        if not disabled:
            for value in pending:
                catalog.add(value, relative)
        pending.clear()

    lines = text.splitlines()
    index = 0
    while index < len(lines):
        line = lines[index]
        index += 1
        if _SCENE_SECTION.match(line):
            flush()
            disabled = False
            continue
        if line.startswith("auto_translate_mode = 2"):
            disabled = True
            continue
        if not re.match(r'^[A-Za-z0-9_/]+ = "', line):
            continue
        # Join the following lines until the quoted value closes.
        while not _SCENE_PROPERTY.fullmatch(line) and index < len(lines):
            line += "\n" + lines[index]
            index += 1
        match = _SCENE_PROPERTY.fullmatch(line)
        if match is None:
            raise ValueError(f"{relative}: unterminated string: {line[:60]!r}")
        name, value = match.group(1), _unescape_scene(match.group(2))
        if name in SCENE_TEXT_PROPERTIES or (name.startswith("popup/item_") and name.endswith("/text")):
            pending.append(value)
    flush()


def _unescape_scene(value: str) -> str:
    return re.sub(r"\\(.)", lambda match: _ESCAPES.get(match.group(1), match.group(1)), value)


# --- Content ----------------------------------------------------------------------------


def extract_content(document: object, relative: str, catalog: Catalog) -> None:
    for record in _records(document):
        _walk_json(record, relative, str(record.get("id", "")), catalog)


def _records(document: object) -> list[dict]:
    if not isinstance(document, dict):
        return []
    records: list[dict] = []
    for value in document.values():
        if isinstance(value, list):
            records.extend(item for item in value if isinstance(item, dict))
    return records


def _walk_json(node: object, relative: str, record_id: str, catalog: Catalog, path: str = "") -> None:
    if isinstance(node, list):
        for item in node:
            _walk_json(item, relative, record_id, catalog, path)
        return
    if not isinstance(node, dict):
        return
    for key, value in node.items():
        here = f"{path}.{key}" if path else key
        note = f"{record_id} {here}".strip()
        if key in TEXT_KEYS and isinstance(value, str):
            catalog.add(value, relative, note=note)
        elif key in TEXT_LIST_KEYS and isinstance(value, list):
            for item in value:
                if isinstance(item, str):
                    catalog.add(item, relative, note=note)
        elif key == "inquiry" and isinstance(value, dict):
            for topic, answer in value.items():
                if has_chinese(topic):
                    catalog.add(topic, relative, note=f"{record_id} inquiry topic")
                _walk_text(answer, relative, f"{record_id} inquiry.{topic}", catalog)
        elif key in ("messages", "chat_msg", "chat_msg_combat", "dodge_messages", "parry_messages", "lines", "shop_front", "summoned"):
            _walk_text(value, relative, note, catalog)
        elif key == "relay_say" and isinstance(value, dict):
            # What the player can say beside the NPC (the 接话 button), and its answers.
            for phrase, answer in value.items():
                if has_chinese(phrase):
                    catalog.add(phrase, relative, note=f"{record_id} relay_say phrase")
                _walk_text(answer, relative, f"{record_id} relay_say.{phrase}", catalog)
        elif key == "valid_learn" and isinstance(value, dict):
            # A skill's valid_learn() lines, keyed by the rule that refuses.
            for rule, line in value.items():
                if isinstance(line, str):
                    catalog.add(line, relative, note=f"{note}.{rule}")
        elif isinstance(value, (dict, list)):
            _walk_json(value, relative, record_id, catalog, here)


def _walk_text(node: object, relative: str, note: str, catalog: Catalog) -> None:
    """Every string under `node` is text; dictionaries in it are walked as records."""
    if isinstance(node, str):
        catalog.add(node, relative, note=note)
    elif isinstance(node, list):
        for item in node:
            _walk_text(item, relative, note, catalog)
    elif isinstance(node, dict):
        for key, value in node.items():
            if key in ID_LIST_KEYS:
                continue
            if isinstance(value, str) and key in LINE_KEYS:
                catalog.add(value, relative, note=f"{note}.{key}")
            elif isinstance(value, (dict, list)):
                _walk_text(value, relative, f"{note}.{key}", catalog)


# --- Catalog ----------------------------------------------------------------------------


def _game_files(repository: Path, suffix: str) -> list[Path]:
    root = repository / GAME
    result: list[Path] = []
    for path in sorted(root.rglob(f"*{suffix}")):
        relative = path.relative_to(root).as_posix()
        if relative.startswith(SKIPPED_DIRECTORIES) or relative in DEV_ONLY_SCENES:
            continue
        result.append(path)
    return result


def build_catalog(repository: Path = REPOSITORY) -> Catalog:
    catalog = Catalog()
    root = repository / GAME
    for path in _game_files(repository, ".tscn"):
        extract_scene(path.read_text(encoding="utf-8"), path.relative_to(root).as_posix(), catalog)
    for path in _game_files(repository, ".gd"):
        extract_gdscript(path.read_text(encoding="utf-8"), path.relative_to(root).as_posix(), catalog)
    manifest = json.loads((repository / MANIFEST).read_text(encoding="utf-8"))
    for name in manifest["files"]:
        path = root / "data" / name
        extract_content(json.loads(path.read_text(encoding="utf-8")), f"data/{name}", catalog)
    return catalog


def lint_repository(repository: Path = REPOSITORY) -> list[str]:
    root = repository / GAME
    errors: list[str] = []
    for path in _game_files(repository, ".gd"):
        errors.extend(lint_concatenation(path.read_text(encoding="utf-8"), path.relative_to(root).as_posix()))
    return errors


def _po_string(text: str) -> str:
    escaped = text.replace("\\", "\\\\").replace('"', '\\"').replace("\t", "\\t").replace("\r", "\\r")
    lines = escaped.split("\n")
    if len(lines) == 1:
        return f'"{lines[0]}"'
    parts = [f'"{line}\\n"' for line in lines[:-1]]
    if lines[-1]:
        parts.append(f'"{lines[-1]}"')
    return '""\n' + "\n".join(parts)


def render_pot(catalog: Catalog) -> str:
    blocks = [HEADER]
    for entry in catalog.entries():
        lines: list[str] = []
        lines.extend(f"#. {note}" for note in entry.notes)
        lines.append("#: " + " ".join(entry.sources))
        if entry.context:
            lines.append(f"msgctxt {_po_string(entry.context)}")
        lines.append(f"msgid {_po_string(entry.msgid)}")
        lines.append('msgstr ""')
        blocks.append("\n".join(lines) + "\n")
    return "\n".join(blocks)


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--repository", type=Path, default=REPOSITORY)
    parser.add_argument("--check", action="store_true", help="fail when the committed template is out of date")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = _parser().parse_args(argv)
    repository = args.repository.resolve()
    text = render_pot(build_catalog(repository))
    target = repository / POT_PATH
    if args.check:
        current = target.read_text(encoding="utf-8") if target.is_file() else ""
        if current != text:
            print(f"ERROR: {POT_PATH} is out of date: run python tools/l10n/extract_pot.py", file=sys.stderr)
            return 1
        print(f"{POT_PATH} is current")
        return 0
    target.parent.mkdir(parents=True, exist_ok=True)
    with target.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write(text)
    print(f"wrote {POT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
